#!/usr/bin/env bash

# the shell integration binds Ctrl-R; 30_atuin loads later and takes it over
# (C4 in .claude/rules/bash.md)
command -v fzf >/dev/null 2>&1 || { return 8; }

__rayrc_main() {
    __rayrc_module_common_setup

    ## Key bindings & completion, generated by install.sh (`fzf --bash`).
    ## Both parts guard themselves with `[[ $- =~ i ]]`.
    [[ -f "${__rayrc_ctl_dir}/shell/fzf.bash" ]] && source "${__rayrc_ctl_dir}/shell/fzf.bash"

    ## open the key bindings and completion in a tmux popup when inside tmux
    ## (ignored outside tmux). Kept out of FZF_DEFAULT_OPTS so that other fzf
    ## callers (ssh(), navi, fzf.vim) stay inline.
    local __rayrc_fzf_tmux_opts="--tmux=center,90%"

    if command -v shfmt &>/dev/null; then
        export FZF_CTRL_R_OPTS="${__rayrc_fzf_tmux_opts} --preview 'echo {2..} | shfmt | bat --color=always --wrap=never --theme Dracula -p -P -l sh' --preview-window down:40%:wrap --tabstop=1 --bind 'ctrl-/:toggle-preview'"
    else
        export FZF_CTRL_R_OPTS="${__rayrc_fzf_tmux_opts} --preview 'echo {2..} | bat --color=always --wrap=never --theme Dracula -p -P -l sh' --preview-window down:40%:wrap --tabstop=1 --bind 'ctrl-/:toggle-preview'"
    fi

    ## default options for fzf
    # export FZF_DEFAULT_OPTS='--height 70% --layout=reverse --border'
    export FZF_DEFAULT_OPTS="--ansi --height 80% --border --preview-window 'right:60%' --layout reverse --margin=1,4 --preview 'bat --color=always --style=header,grid --line-range :200 {}'"
    export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=info:#afaf87,prompt:#d7005f,pointer:#af5fff
    --color=marker:#87ff00,spinner:#af5fff,header:#87afaf'


    # set env variables for fzf
    export FZF_DEFAULT_COMMAND='fd --type f --follow --exclude .git'


    ## CTRL+T to list files
    export FZF_CTRL_T_COMMAND='fd --type f --color always --hidden --follow --exclude .git'
    export FZF_CTRL_T_OPTS="${__rayrc_fzf_tmux_opts} --ansi --layout=reverse --height 70% --border --margin 0,0 --preview-window 'right:60%' --preview 'bat --color=always --style=numbers,grid --line-range :200 {}'"


    ## ALT+C to quick change directory
    # export FZF_ALT_C_COMMAND=''
    export FZF_ALT_C_OPTS="${__rayrc_fzf_tmux_opts} --no-preview"


    ## ** + TAB completion
    export FZF_COMPLETION_OPTS="${__rayrc_fzf_tmux_opts}"

    source "${__rayrc_ctl_dir}/functions.sh"
}

__rayrc_main
unset -f __rayrc_main
