name: on-click installation check
on: [push, pull_request, workflow_dispatch]
jobs:
  env_check:
    strategy:
      fail-fast: false
      matrix:
        #
        # maybe windows some time later
        os: [macos-11, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install zsh, not really need
        if: matrix.os == 'macos-11'
        run: |
          # brew install curl git zsh
          brew install zsh
          # sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

          echo "##### pwd #####"
          pwd
          echo "##### ls -ahl #####"
          ls -ahl

      - name: show some variables for linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          echo "##### pwd #####"
          pwd
          echo "##### ls -ahl #####"
          ls -ahl
          echo "##### whoami #####"
          whoami
          echo "\$HOME: $HOME"

      - name: source ./.rayrc/install
        run: |
          source ./.rayrc/install
