name: on-click installation check
on: [push, pull_request, workflow_dispatch]
jobs:
  env_check:
    strategy:
      fail-fast: false
      matrix:
        #
        # maybe windows some time later
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      ######################################################################
      # macos
      ######################################################################
      - name: install zsh, not really need
        if: matrix.os == 'macos-11'
        run: |
          # brew install curl git zsh
          if ! command -v zsh >& /dev/null; then
            brew install zsh
          fi
          # sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

          echo "##### pwd #####"
          pwd
          echo "##### ls -ahl #####"
          ls -ahl

      - name: ./install for macos
        if: matrix.os == 'macos-11'
        run: |
          zsh ./install

      ######################################################################
      # linux
      ######################################################################
      - name: show some variables for linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          echo "##### pwd #####"
          pwd
          echo "##### ls -ahl #####"
          ls -ahl
          echo "##### whoami #####"
          whoami
          echo "\$HOME: $HOME"

      - name: source ./install for linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          source ./install
          # exec bash
